<?php

namespace AppBundle\Repository;

/**
 * ConfirmationTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmationTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
