<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNewestProducts()
    {
        $products = $this->createQueryBuilder('p')
        ->orderBy('p.creationDate', 'DESC')
        ->setMaxResults(6)
        ->getQuery()
        ->getResult();

        return $products;;
    }

    public function getMostViewedProducts()
    {
        $products = $this->createQueryBuilder('p')
            ->orderBy('p.numVisits', 'DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();

        return $products;;
    }
}
