<?php

namespace AppBundle\Repository;

/**
 * RedirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectionRepository extends \Doctrine\ORM\EntityRepository
{
}
