#app:
    #resource: "@AppBundle/Controller/"
    #type:     annotation #commented this to create routes on yaml file

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#actions that may handle a form need to accept also post request
# /user/* refers to the private area of the application. So controllers must extend from PrivateBaseController
# the rest of pages that do not require authentication to render must extend PublicBaseController
# Controller and BaseController which extends Controller must not be extended on any endpoint controller.

homepage:
  path: /
  defaults:
    _controller: AppBundle:HomePage:show
    _format: html
  methods:
    - GET


welcome:
  path: /welcome
  defaults:
    _controller: AppBundle:HomePage:welcome
    _format: html
  methods:
    - GET

profile:
  path: /user/{username}
  defaults:
    _controller: AppBundle:Profile:show
    _format: html
  methods:
    - GET

profile_products:
  path: /user/{username}/products
  defaults:
    _controller: AppBundle:Product:show
    _format:
  methods:
    - GET
    - POST #will be used to process the delete form submit

product_add:
  path: /user/{username}/product/add
  defaults:
    _controller: AppBundle:Product:add
    _format: html
  methods:
    - GET
    - POST #will be used also to process the add form submit

product_delete:
  path: /user/{username}/product/edit/{uuid}
  defaults:
    _controller: AppBundle:Product:edit
    _format: html
  methods:
    - GET
    - POST #will be used to process edit and delete form submit

profile_edit:
  path: /user/{username}/edit-profile
  defaults:
    _controller: AppBundle:Profile:edit
    _format: html
  methods:
    - GET

profile_recharge:
  path: /user/{username}/recharge
  defaults:
    _controller: AppBundle:Profile:recharge
    _format: html
  methods:
    - GET
    - POST #will be used to process recharge form

products:
  path: /products
  defaults:
    _controller: AppBundle:Products:show
    _format: html
  methods:
    - GET

search:
  path: /search
  defaults:
    _controller: AppBundle:Search:showResults
    _format: html
  methods:
    - POST #handles the form received on search and loads the results

popular:
  path: /products/popular
  defaults:
    _controller: AppBundle:Products:showPopular
    _format: html
  methods:
    - GET

buy_item:
  path: /buy/{uuid}
  defaults:
    _controller: AppBundle:Buy:show
    _format: html
  methods:
    - GET
    - POST # used to process buy request form

#register:
#  path: /register
#  defaults:
#    _controller: AppBundle:Register:show
#    _format: html
#  methods:
#    - GET
#    - POST #will be used to process register form

register_confirm:
  path: /confirm/{uuid}
  defaults:
    _controller: AppBundle:Register:confirm
    _format: html
  methods:
    - GET

authenticate:
  path: /auth #authenticates user and attaches it to the actual session
  defaults:
    _controller: AppBundle:Authentication:auth
    _format: html
  methods:
    - POST # used to authenticate users wherever the login form was captured from

#login:
#  path: /login
#  defaults:
#    _controller: AppBundle:Authentication:show
#    _format: html
#  methods:
#    - GET
#    - POST #submit login form

#logout:
#  path: /logout #logs out authenticated user on current session
#  defaults:
#    _controller: AppBundle:
#    _format: html
#  methods:
#    - GET # just has to deattach session and stuff and redirect to homepage

welcome:
  path: /welcome
  defaults:
    _controller: AppBundle:
    _format:
  methods:
    - GET
