#app:
    #resource: "@AppBundle/Controller/"
    #type:     annotation #commented this to create routes on yaml file

kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor


#actions that may handle a form need to accept also post request
# /user/* refers to the private area of the application. So controllers must extend from PrivateBaseController
# the rest of pages that do not require authentication to render must extend PublicBaseController
# Controller and BaseController which extends Controller must not be extended on any endpoint controller.

# All above is bullshit, symfony security configuration allows to forget about that and if wanted maybe use a BaseController
# to make custom stuff but differentiation of private/public area is done thorugh the use of roles for the user and everything.
# Refer to symfony security documentation to see how to see the role/authentication_status for each session and stuff.

homepage:
  path: /
  defaults:
    _controller: AppBundle:HomePage:show
    _format: html
  methods:
    - GET


welcome:
  path: /welcome
  defaults:
    _controller: AppBundle:HomePage:welcome
    _format: html
  methods:
    - GET


profile_products:
  path: /user/products
  defaults:
    _controller: AppBundle:Profile:showProducts
    _format:
  methods:
    - GET
    - POST #will be used to process the delete form submit

product_add:
  path: /user/add-product
  defaults:
    _controller: AppBundle:Profile:addProduct
    _format: html
  methods:
    - GET
    - POST #will be used also to process the add form submit

product_delete:
  path: /user/delete/{category}/{uuid}
  requirements:
    category: "table|paddle|ball|robot|accessories|other"
  defaults:
    _controller: AppBundle:Product:delete
    _format: html
  methods:
    - GET

product_edit:
  path: /user/edit/{category}/{uuid}
  requirements:
   category: "table|paddle|ball|robot|accessories|other"
  defaults:
   _controller: AppBundle:Product:edit
   _format: html
  methods:
   - GET

profile_edit:
  path: /user/{username}/edit-profile
  defaults:
    _controller: AppBundle:Profile:edit
    _format: html
  methods:
    - GET

profile_recharge:
  path: /user/recharge
  defaults:
    _controller: AppBundle:Profile:recharge
    _format: html
  methods:
    - GET
    - POST #will be used to process recharge form


profile:
  path: /user/{username}
  defaults:
    _controller: AppBundle:Profile:show
    _format: html
  methods:
    - GET


products:
  path: /products
  defaults:
    _controller: AppBundle:Products:show
    _format: html
  methods:
    - GET

search:
  path: /search
  defaults:
    _controller: AppBundle:Search:showResults
    _format: html
  methods:
    - POST #handles the form received on search and loads the results

popular:
  path: /products/popular
  defaults:
    _controller: AppBundle:Products:showPopular
    _format: html
  methods:
    - GET

buy_item:
  path: /buy/{uuid}
  defaults:
    _controller: AppBundle:Buy:show
    _format: html
  methods:
    - GET
    - POST # used to process buy request form

register:
  path: /register
  defaults:
    _controller: AppBundle:Register:show
    _format: html
  methods:
    - GET
    - POST #will be used to process register form

registration_success:
  path: /register/confirmation
  defaults:
    _controller: AppBundle:Register:success
    _format: html
  methods:
    - GET

confirmation:
  path: /confirm/{token}
  defaults:
    _controller: AppBundle:Register:confirm
    _format: html
  methods:
    - GET


login:
  path: /login
  defaults:
    _controller: AppBundle:Authentication:show
    _format: html
  methods:
    - GET


login_check:
  path: /login_check
  methods:
    - POST

logout:
  path: /logout #logs out authenticated user on current session
  defaults:
    _controller: AppBundle:
    _format: html
  methods:
    - GET # just has to deattach session and stuff and redirect to homepage

product_show:
  path: /{category}/{uuid} #category must be reserved words that cannot appear on any route so it will default here
  requirements:
    category: "table|paddle|ball|robot|accessories|other"
  defaults:
    _controller: AppBundle:Product:show
    _format:
  methods:
    - GET

welcome:
  path: /welcome
  defaults:
    _controller: AppBundle:
    _format:
  methods:
    - GET

welcome:
  path: /welcome
  defaults:
    _controller: AppBundle:
    _format:
  methods:
    - GET