# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
# parameters:
#    parameter_name: value

services:
  app.form.registration:
    class: AppBundle\Form\RegistrationType
    tags:
      - { name: form.type, alias: app_user_registration }

  app.form.login_type:
    class: AppBundle\Form\LoginType
    arguments:
      router: "@router"
    tags:
      - { name: form.type, alias: authenticate }

  app.metadata.user:
      class: Doctrine\ORM\Mapping\ClassMetadata
      factory_service: doctrine # this is an instance of Registry
      factory_method: getRepository
      arguments: [ AppBundle\Entity\User ]

  app.username_email_user_provider:
      class: AppBundle\Repository\UserRepository
      arguments:
          em: "@doctrine.orm.entity_manager"
          class: "@app.metadata.user"



  app.service.mailer.mailer_repository:
    class: AppBundle\Services\Mailer\MailerRepository
    arguments:
      mailer: "@mailer"                 # {type: "service", id: "mailer"}
      router: "@router"                 # {type: "service", id: "router"}
      templating: "@twig"               # {type: "service", id: "templating"}
      parameters:
        confirmation.template: 'mail/confirmation.mail.twig'
        from_email: %email%

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


